FROM selenium/standalone-firefox

RUN sudo apt update
RUN sudo apt install -y python3 && sudo apt install -y python3-pip && pip3 install selenium && pip3 install requests && sudo apt install -y nano && sudo pip3 install requests
RUN sudo pip3 install --upgrade selenium

WORKDIR /auto

COPY . /auto/

ENV ip_server="172.17.0.2"

RUN sudo chmod +x /auto/*
